### ISSUE TITLE
php bin/hyperf.php vendor:publish报错

### ISSUE THREAD

**Issue by leinZero** [hyperf/gotask#20]
版本：hyperf2.0

php bin/hyperf.php vendor:publish -vvv

In Input.php line 76:
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Not enough arguments (missing: "package").              
                                                          

Exception trace:
  at /home/aa/project/vvapi/vendor/symfony/console/Input/Input.php:76
 Symfony\Component\Console\Input\Input->validate() at /home/aa/project/vvapi/vendor/symfony/console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /home/aa/project/vvapi/vendor/symfony/console/Application.php:929
 Symfony\Component\Console\Application->doRunCommand() at /home/aa/project/vvapi/vendor/symfony/console/Application.php:264
 Symfony\Component\Console\Application->doRun() at /home/aa/project/vvapi/vendor/symfony/console/Application.php:140
 Symfony\Component\Console\Application->run() at /home/aa/project/vvapi/bin/hyperf.php:21
 {closure}() at /home/aa/project/vvapi/bin/hyperf.php:22

**Comment by Reasno** [comment]
php bin/hyperf.php vendor:publish hyperf/gotask
