### ISSUE TITLE
调用mongo报错

### ISSUE THREAD

**Issue by leinZero** [hyperf/gotask#21]
hyperf2.0，用的example里的代码：

$task = new SocketIPCSender('127.0.0.1:6001');
        $rs = $task->call('MongoProxy.Find', ['Database' => 'test', 'Collection' => 'test', 'Filter' => ['a'=>2], 'Opts' => [['Skip' => 0, 'Limit' => 2]]]);

错误信息：
error 'base64Codec: invalid input, error found in #0 byte of ...|{"Database|..., bigger context ...|{"Database":"test","Collection":"test","Filter":{"|...' on 'Hyperf\GoTask\Relay\CoroutineSocketRelay'

**Comment by Reasno** [comment]
example没有更新到2.2.0版本，可以看一下https://github.com/hyperf/gotask/blob/master/tests/Cases/MongoDBTest.php 这里的用法。

**Comment by leinZero** [comment]
用的2.2版，问题依旧

**Comment by Reasno** [comment]
> 用的2.2版，问题依旧

是example里给的使用方式不是最新的。现在已经更新了。

**Comment by leinZero** [comment]
$client = make(MongoClient::class);
$collection = $client->database('test')->collection('test');
$result = $collection->find(['user_id' => 0], ['skip' => 0, 'limit' => 1]);
print_r($result);

**Comment by leinZero** [comment]
用的是MongoClient这个类

**Comment by leinZero** [comment]
貌似是因为mongo加了用户密码认证就不行了：mongodb://ssaa:123456@192.168.100.110:27017

**Comment by Reasno** [comment]
> 了用户

用户名密码要在config里配置呀

**Comment by Reasno** [comment]
这里有一个hyperf下使用的demo： https://github.com/reasno/fastmongo
