### ISSUE TITLE
开启go2php的情况下 会导致 http 服务器无法启动 想问下 为啥不放在进程中

### ISSUE THREAD

**Issue by Niexiawei** [hyperf/gotask#27]
![image](https://user-images.githubusercontent.com/29922984/93170982-d02dc800-f75a-11ea-9851-f16589216006.png)

hyperf2.0  用的不是协程服务器

**Comment by Reasno** [comment]
为什么http服务器无法启动？

**Comment by Niexiawei** [comment]
我也没找到原因 只要开启了go2php 控制台输出就和上面一样 框架自带的HTTP服务器就不启动了 使用的是 试了用 ip 和 unix 地址 都不行

**Comment by Reasno** [comment]
> 我也没找到原因 只要开启了go2php 控制台输出就和上面一样 框架自带的HTTP服务器就不启动了 试了 用 ip 和 unix 地址 都不行

无法复现

**Comment by Niexiawei** [comment]
我自己在试试  可能和其他事件有冲突 

能问个问题吗  go2php 这个为什么不单独放在进程中

**Comment by Niexiawei** [comment]
去除了代码中的 AfterWorkerStart 现在可以正常启动

不过 不会显示 HTTP Server listening at xxxxxx 这种提示了

![image](https://user-images.githubusercontent.com/29922984/93191195-d5007500-f776-11ea-829a-59b35fa321f9.png)

hyperf  这边的服务器监听的 也是 AfterWorkerStart  这个事件  不知道是不是有冲突

**Comment by Reasno** [comment]
> 去除了代码中的 AfterWorkerStart 现在可以正常启动
> 
> 不过 不会显示 HTTP Server listening at xxxxxx 这种提示了
> 
> ![image](https://user-images.githubusercontent.com/29922984/93191195-d5007500-f776-11ea-829a-59b35fa321f9.png)
> 
> hyperf 这边的服务器监听的 也是 AfterWorkerStart 这个事件 不知道是不是有冲突

这listener是你自己的还是框架里的？

**Comment by Reasno** [comment]
> 我自己在试试 可能和其他事件有冲突
> 
> 能问个问题吗 go2php 这个为什么不单独放在进程中

可以放到单独的进程中其实。

**Comment by Niexiawei** [comment]
我截图的这个是 框架里面的 负责HTTP WS TCP 等Server 启动的

**Comment by Niexiawei** [comment]
![image](https://user-images.githubusercontent.com/29922984/93237990-6a215f00-f7b3-11ea-8d56-11534fe2ff4f.png)

我尝试在外面套了一层协程 发现就都正常了 
不知道这样会不会有啥问题不

**Comment by Reasno** [comment]
> ![image](https://user-images.githubusercontent.com/29922984/93237990-6a215f00-f7b3-11ea-8d56-11534fe2ff4f.png)
> 
> 
> 
> 我尝试在外面套了一层协程 发现就都正常了 
> 
> 不知道这样会不会有啥问题不

应该不会有问题 可以提个PR
