### ISSUE TITLE
composer 安装 包冲突 建议升级一下依赖包的版本

### ISSUE THREAD

**Issue by yhuaao** [hyperf/gotask#55]
![image](https://user-images.githubusercontent.com/19657556/173536773-191cdd7a-5fac-4196-bec2-c1beb5b45d5e.png)

**Comment by try-to** [comment]
+1

**Comment by luorenshu** [comment]
+1

**Comment by hh-Ink** [comment]
+1

**Comment by try-to** [comment]
2023年了，这个库是放弃了吗？不支持3.0+了？
