### ISSUE TITLE
hyperf3.1不支持

### ISSUE THREAD

**Issue by bain2018** [hyperf/gotask#67]
Problem 1
    - hyperf/gotask[dev-dependabot/composer/spiral/goridge-tw-2.4or-tw-4.0, dev-master, v3.0.0] require symfony/event-dispatcher ^6.3 -> found symfony/event-dispatcher[v6.3.0-BETA1, ..., 6.4.x-dev] but the package is fixed to v7.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - hyperf/gotask[v1.0.0, ..., v1.0.1] require hyperf/command ^1.1 -> found hyperf/command[v1.1.0, ..., 1.1.x-dev] but it conflicts with your root composer.json require (~3.1.0).
    - hyperf/gotask[0.0.3, ..., v0.3.0, v1.0.2, v2.0.0, ..., v2.1.1] require hyperf/pool ^1.1 -> found hyperf/pool[v1.1.0, ..., 1.1.x-dev] but the package is fixed to v3.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - hyperf/gotask[v2.2.0, ..., v2.2.3] require hyperf/pool ~2.0.0 -> found hyperf/pool[v2.0.0, v2.0.3, v2.0.12, 2.0.x-dev] but the package is fixed to v3.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - hyperf/gotask[dev-dependabot/composer/friendsofphp/php-cs-fixer-tw-2.14or-tw-3.0, dev-perm, v2.1.x-dev, ..., v2.2.10] require hyperf/pool ^2.0.0 -> found hyperf/pool[v2.0.0, ..., 2.2.x-dev] but the package is fixed to v3.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - hyperf/gotask v3.0.0-alpha requires symfony/event-dispatcher ^5.1 -> found symfony/event-dispatcher[v5.1.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v7.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires hyperf/gotask * -> satisfiable by hyperf/gotask[dev-dependabot/composer/spiral/goridge-tw-2.4or-tw-4.0, dev-dependabot/composer/friendsofphp/php-cs-fixer-tw-2.14or-tw-3.0, dev-master, dev-perm, 0.0.3, ..., v0.3.0, v1.0.0, v1.0.1, v1.0.2, v2.0.0, ..., v2.2.10, v3.0.0-alpha, v3.0.0, 9999999-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require hyperf/gotask:*" to figure out if any version is installable, or "composer require hyperf/gotask:^2.1" if you know which you need.

**Comment by chaodada** [comment]
我也遇到了这个问题
